### PR TITLE
Fix mixin calls

### PR DESCRIPTION
**Pull request by jzelez**

### CODE REVIEW

**Comment by shirohana** [comment]
Omg how a stupid mistake I made ｡ﾟヽ(ﾟ´Д`)ﾉﾟ｡

Is there any tool to help to lint my `.styl` codes (´；ω；｀)？

Thanks for your contribution ฅ' ω 'ฅ

**Comment by shirohana** [comment]
I'll publish a patch version to NPM like `0.7.0-patch.1`

**Comment by jzelez** [comment]
There is `stylint` but I don't think it would catch the above issue.

**Comment by shirohana** [comment]
That was so sad (´-ωก`)

I can find the mixins which was no parentheses after by `the silver searcher`, but it is not strict and it will make contributing more difficult...

Maybe I should add `contribution guide` section in `README` and notice myself to avoid making this trouble again (˘̩̩̩ ω ˘̩ƪ)

**Comment by shirohana** [comment]
After a time of code reviewing, `0.7.0-patch.1` available on NPM now ฅ' ω 'ฅ

https://github.com/shirohana/bulma.stylus/releases/tag/v0.7.0-patch.1

**Pull request merged**
